# Generated by Django 5.2.7 on 2025-10-15 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('recharge', 'Recharges'), ('account', 'Achat compte')], default='recharge', max_length=30),
        ),
    ]
