# Generated by Django 5.2.7 on 2025-10-22 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='requires_player_id',
            field=models.BooleanField(default=False, help_text='Afficher le champ ID joueur pour ce produit', verbose_name='Requiert ID joueur'),
        ),
    ]
