# Generated by Django 5.2.7 on 2025-10-19 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_category_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='category_type',
            field=models.CharField(choices=[('recharge', 'Recharge'), ('account', 'Compte de Jeu'), ('other', 'Autre')], default='recharge', help_text="Définit si c'est une recharge ou un compte", max_length=20, verbose_name='Type de catégorie'),
        ),
        migrations.AddField(
            model_name='product',
            name='account_level',
            field=models.IntegerField(blank=True, help_text='Pour les comptes de jeux uniquement', null=True, verbose_name='Niveau du compte'),
        ),
        migrations.AddField(
            model_name='product',
            name='account_rank',
            field=models.CharField(blank=True, help_text='Ex: Elite, Héroïque, Diamant...', max_length=100, verbose_name='Rang du compte'),
        ),
        migrations.AddField(
            model_name='product',
            name='diamonds_included',
            field=models.IntegerField(blank=True, help_text='Nombre de diamants dans le compte', null=True, verbose_name='Diamants inclus'),
        ),
        migrations.AddField(
            model_name='product',
            name='has_elite_pass',
            field=models.BooleanField(default=False, help_text='Pour les comptes Free Fire', verbose_name='Possède Elite Pass'),
        ),
        migrations.AddField(
            model_name='product',
            name='has_rare_skins',
            field=models.BooleanField(default=False, help_text='Pour les comptes de jeux', verbose_name='Possède des skins rares'),
        ),
        migrations.AddField(
            model_name='product',
            name='image_2',
            field=models.ImageField(blank=True, help_text='Image supplémentaire pour montrer le compte', null=True, upload_to='products/', verbose_name='Image 2 (optionnel)'),
        ),
        migrations.AddField(
            model_name='product',
            name='image_3',
            field=models.ImageField(blank=True, help_text='Image supplémentaire pour montrer le compte', null=True, upload_to='products/', verbose_name='Image 3 (optionnel)'),
        ),
        migrations.AddField(
            model_name='product',
            name='important_info',
            field=models.TextField(blank=True, help_text='Informations à afficher en évidence (garanties, conditions, etc.)', verbose_name='Informations importantes'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='products/', verbose_name='Image principale'),
        ),
    ]
