# Generated by Django 5.2.7 on 2025-10-19 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_category_category_type_product_account_level_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountProduct',
            fields=[
            ],
            options={
                'verbose_name': 'Compte de Jeu',
                'verbose_name_plural': '🎮 Comptes de Jeux',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('store.product',),
        ),
        migrations.CreateModel(
            name='RechargeProduct',
            fields=[
            ],
            options={
                'verbose_name': 'Recharge',
                'verbose_name_plural': '📱 Recharges (Diamants, etc.)',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('store.product',),
        ),
        migrations.RemoveField(
            model_name='category',
            name='category_type',
        ),
        migrations.RemoveField(
            model_name='product',
            name='has_rare_skins',
        ),
        migrations.RemoveField(
            model_name='product',
            name='image_2',
        ),
        migrations.RemoveField(
            model_name='product',
            name='image_3',
        ),
        migrations.RemoveField(
            model_name='product',
            name='important_info',
        ),
        migrations.AddField(
            model_name='product',
            name='account_region',
            field=models.CharField(blank=True, choices=[('', 'Non spécifié'), ('afrique', 'Afrique'), ('europe', 'Europe'), ('asie', 'Asie'), ('amerique', 'Amérique'), ('oceanie', 'Océanie')], help_text='Ex: Afrique, Europe, Asie, etc.', max_length=50, verbose_name='Région du compte'),
        ),
        migrations.AddField(
            model_name='product',
            name='email_changeable',
            field=models.BooleanField(default=True, verbose_name='Email changeable'),
        ),
        migrations.AddField(
            model_name='product',
            name='facebook_linked',
            field=models.BooleanField(default=False, verbose_name='Facebook lié'),
        ),
        migrations.AddField(
            model_name='product',
            name='internal_notes',
            field=models.TextField(blank=True, help_text="Notes visibles uniquement par l'admin (non affichées sur le site)", verbose_name='Notes internes'),
        ),
        migrations.AddField(
            model_name='product',
            name='pets_list',
            field=models.TextField(blank=True, help_text='Listez les pets disponibles (un par ligne)', verbose_name='Liste des pets'),
        ),
        migrations.AddField(
            model_name='product',
            name='phone_linked',
            field=models.BooleanField(default=False, verbose_name='Numéro de téléphone lié'),
        ),
        migrations.AddField(
            model_name='product',
            name='skins_list',
            field=models.TextField(blank=True, help_text='Listez les skins rares (un par ligne)', verbose_name='Liste des skins/bundles'),
        ),
        migrations.AddField(
            model_name='product',
            name='total_matches',
            field=models.IntegerField(blank=True, null=True, verbose_name='Nombre total de matchs'),
        ),
        migrations.AddField(
            model_name='product',
            name='vehicles_list',
            field=models.TextField(blank=True, help_text='Listez les véhicules disponibles (un par ligne)', verbose_name='Liste des véhicules/skyboards'),
        ),
        migrations.AddField(
            model_name='product',
            name='weapons_list',
            field=models.TextField(blank=True, help_text='Listez les armes disponibles (un par ligne)', verbose_name='Liste des armes'),
        ),
        migrations.AddField(
            model_name='product',
            name='win_rate',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Ex: 65.50 pour 65.50%', max_digits=5, null=True, verbose_name='Taux de victoire (%)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='account_level',
            field=models.IntegerField(blank=True, help_text='Ex: 50, 65, 80, etc.', null=True, verbose_name='Niveau du compte'),
        ),
        migrations.AlterField(
            model_name='product',
            name='account_rank',
            field=models.CharField(blank=True, help_text='Ex: Héroïque, Grand Maître, Conqueror, etc.', max_length=50, verbose_name='Rang/Grade'),
        ),
        migrations.AlterField(
            model_name='product',
            name='diamonds_included',
            field=models.IntegerField(blank=True, help_text='Nombre de diamants sur le compte', null=True, verbose_name='Diamants inclus'),
        ),
        migrations.AlterField(
            model_name='product',
            name='has_elite_pass',
            field=models.BooleanField(default=False, verbose_name='Elite Pass actif'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='products/', verbose_name='Image'),
        ),
    ]
