# Generated by Django 5.2.7 on 2025-10-22 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='player_id',
            field=models.CharField(blank=True, help_text='ID du joueur pour les recharges automatiques', max_length=50, verbose_name='ID Joueur'),
        ),
    ]
